version: "3"

services:
  chirpstack:
    image: chirpstack/chirpstack:4
    command: -c /etc/chirpstack
    restart: unless-stopped
    volumes:
      - ./configuration/chirpstack:/etc/chirpstack
      - ./lorawan-devices:/opt/lorawan-devices
    depends_on:
      - postgres
      - mosquitto
      - redis
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - REDIS_HOST=redis
      - POSTGRESQL_HOST=postgres
    networks:
      - chirpstack-internal
      - proxy
    ports:
      - 8080:8080
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.chirpstack.entrypoints=web, websecure"
      - "traefik.http.routers.chirpstack.rule=Host(`<your-domain-name>`)"
      - "traefik.http.routers.chirpstack.tls=true"
      - "traefik.http.routers.chirpstack.tls.certresolver=production"

  chirpstack-gateway-bridge-eu868:
    image: chirpstack/chirpstack-gateway-bridge:3.14
    restart: unless-stopped
    networks:
      - chirpstack-internal
    ports:
      - 1700:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge-eu868:/etc/chirpstack-gateway-bridge
    depends_on: 
      - mosquitto

  chirpstack-gateway-bridge-us915_0:
    image: chirpstack/chirpstack-gateway-bridge:3.14
    restart: unless-stopped
    networks:
      - chirpstack-internal
    ports:
      - 1701:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge-us915_0:/etc/chirpstack-gateway-bridge
    depends_on: 
      - mosquitto

  chirpstack-gateway-bridge-us915_1:
    image: chirpstack/chirpstack-gateway-bridge:3.14
    restart: unless-stopped
    networks:
      - chirpstack-internal
    ports:
      - 1702:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge-us915_1:/etc/chirpstack-gateway-bridge
    depends_on: 
      - mosquitto

  chirpstack-gateway-bridge-as923_2:
    image: chirpstack/chirpstack-gateway-bridge:3.14
    restart: unless-stopped
    networks:
      - chirpstack-internal
    ports:
      - 1703:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge-as923_2:/etc/chirpstack-gateway-bridge
    depends_on: 
      - mosquitto

  chirpstack-gateway-bridge-kr920:
    image: chirpstack/chirpstack-gateway-bridge:3.14
    restart: unless-stopped
    networks:
      - chirpstack-internal
    ports:
      - 1704:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge-kr920:/etc/chirpstack-gateway-bridge
    depends_on: 
      - mosquitto

  chirpstack-rest-api:
    image: chirpstack/chirpstack-rest-api:4
    restart: unless-stopped
    command: --server chirpstack:8080 --bind 0.0.0.0:8090 --insecure
    networks:
      - chirpstack-internal
    ports:
      - 8090:8090
    depends_on:
      - chirpstack

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
    networks:
      - chirpstack-internal

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks:
      - chirpstack-internal

  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    networks:
      - chirpstack-internal
    ports:
      - 1883:1883
    volumes: 
      - ./configuration/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  postgresqldata:
  redisdata:

networks:
  chirpstack-internal:
    external: false
  proxy:
    external: true
